### ISSUE TITLE
Add more E2E tests

### ISSUE THREAD

**Issue by weebao** [beatcode-official/client#9]

**Comment by Tristesse02** [comment]
- [x] Added front end tests on register page (check minimum, maximum characters input, validate email input, validate password input including minimum length required and match password checking)
- [x] Added checks for visibility of necessary svgs and images on main page, register page, and login page
- [x] Added front-end failed login test: notifications and warning for user re-input
- [x] Added check for sufficient component on success register page
- [x] Added local check for successful login, home components availability, custom mode entry (button click), and check room creation stability
Total of 34 tests cases including CI and Local
